<%@ page language="java" %>

<%!
/* authentication stuff - robert
 * -----------------------------
 */
// create DocumentBean instance for all JSP requests
digilib.servlet.DocumentBean docBean = new digilib.servlet.DocumentBean();

// initialize DocumentBean instance in JSP init
public void jspInit() {
    try {
        // set servlet init-parameter
        docBean.setConfig(getServletConfig());
    } catch (javax.servlet.ServletException e) {
        System.out.println(e);
    }
}
%>

<%
// parse the query
digilib.servlet.DigilibRequest dlRequest = new digilib.servlet.DigilibRequest(request);
// add number of pages from DocBean
dlRequest.setPt(docBean.getNumPages(dlRequest));
%>

// Automatically generated JavaScript snippet with parameters

var dlreqPt = <%= dlRequest.getPt() %>; // total number of pages (generated by sevlet)

var dlreqRequestPath = "<%= dlRequest.getRequestPath() %>";  // url of the page/document			
var dlreqFn = "<%= dlRequest.getFn() %>"; // url of the page/document
var dlreqFilePath = "<%= dlRequest.getFilePath() %>"; // effective path of the page/document
var dlreqPn = "<%= dlRequest.getPn() %>"; // page number
var dlreqDw = "<%= dlRequest.getDw() %>"; // width of client in pixels
var dlreqDh = "<%= dlRequest.getDh() %>"; // height of client in pixels
var dlreqWx = "<%= dlRequest.getWx() %>"; // left edge of image (float from 0 to 1)
var dlreqWy = "<%= dlRequest.getWy() %>"; // top edge in image (float from 0 to 1)
var dlreqWw = "<%= dlRequest.getWw() %>"; // width of image (float from 0 to 1)
var dlreqWh = "<%= dlRequest.getWh() %>"; // height of image (float from 0 to 1)
var dlreqWs = "<%= dlRequest.getWs() %>"; // scale factor
var dlreqMo = "<%= dlRequest.getMo() %>"; // special options like 'fit' for gifs
var dlreqMk = "<%= dlRequest.getMk() %>"; // marks
var dlreqBaseURL = "<%= dlRequest.getBaseURL() %>"; // base URL (from http:// to below /servlet)
