name: Docker image build

on:
  push:
    branches:
      - master
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to the Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push master branch snapshot
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          file: build/docker/Dockerfile
          push: true
          tags: |
            robcast/digilib:snapshot
            ghcr.io/robcast/digilib:snapshot

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/metadata-action@v4
        with:
          images: |
            robcast/digilib
            ghcr.io/robcast/digilib

      - name: Build and push tagged version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v3
        with:
          file: build/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
