name: digilib Docker Image CI

on:
  push:
    branches: 
    - master
    tags:
    - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test ref
      #run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      run: echo "GIT_TAG=${GITHUB_REF/refs\/heads\//}" >> $GITHUB_ENV
    - run: echo "my git_tag=${{ env.GIT_TAG }}"
    - run: /bin/false
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push snapshot to Docker Hub
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: docker/build-push-action@v2
      with:
        file: build/docker/Dockerfile
        push: true
        tags: robcast/digilib:snapshot
    - name: Push release to Docker Hub
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v2
      with:
        file: build/docker/Dockerfile
        push: true
        tags: robcast/digilib:${{ github.ref }}
      
